// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/abi/abi_loong64.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/abi/abi_loong64.go:1
// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package abi

const (
	// See abi_generic.go.

	// R4 - R19
	IntArgRegs = 16

	// F0 - F15
	FloatArgRegs = 16

	EffectiveFloatRegSize = 8
)
