// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/abi/map_select_noswiss.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/abi/map_select_noswiss.go:1
// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build !goexperiment.swissmap

package abi

// See comment in map_select_swiss.go.
type mapType = OldMapType
