// Code generated by go tool dist; DO NOT EDIT.

package ssa

func rewriteValueARM64latelower(v *Value) bool { panic("unused during bootstrap") }
func rewriteBlockARM64latelower(b *Block) bool { panic("unused during bootstrap") }
