// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/cmd/link/internal/ld/outbuf_notdarwin.go

//line /home/erik/Uni/Advocate/goPatch/src/cmd/link/internal/ld/outbuf_notdarwin.go:1
// Copyright 2020 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build !darwin

package ld

func (out *OutBuf) purgeSignatureCache() {}
