// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_heapminimum512kib_on.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_heapminimum512kib_on.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.heapminimum512kib

package goexperiment

const HeapMinimum512KiB = true
const HeapMinimum512KiBInt = 1
