// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_synchashtriemap_off.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_synchashtriemap_off.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.synchashtriemap

package goexperiment

const SyncHashTrieMap = false
const SyncHashTrieMapInt = 0
