// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_boringcrypto_on.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_boringcrypto_on.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.boringcrypto

package goexperiment

const BoringCrypto = true
const BoringCryptoInt = 1
