// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_newinliner_on.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_newinliner_on.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.newinliner

package goexperiment

const NewInliner = true
const NewInlinerInt = 1
