// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_cgocheck2_on.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_cgocheck2_on.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.cgocheck2

package goexperiment

const CgoCheck2 = true
const CgoCheck2Int = 1
