// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_jsonv2_on.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_jsonv2_on.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.jsonv2

package goexperiment

const JSONv2 = true
const JSONv2Int = 1
