// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_dwarf5_on.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_dwarf5_on.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.dwarf5

package goexperiment

const Dwarf5 = true
const Dwarf5Int = 1
