// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_cacheprog_off.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/goexperiment/exp_cacheprog_off.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.cacheprog

package goexperiment

const CacheProg = false
const CacheProgInt = 0
