// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Arbeit/Advocate/goPatch/src/internal/goexperiment/exp_preemptibleloops_on.go

//line /home/erik/Arbeit/Advocate/goPatch/src/internal/goexperiment/exp_preemptibleloops_on.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.preemptibleloops

package goexperiment

const PreemptibleLoops = true
const PreemptibleLoopsInt = 1
