// OOSC-FILE_START

// Copyright (c) 2024 Erik Kassubek
//
// File: oosc_routine.go
// Brief: Functionality for the routines
//
// Author: Erik Kassubek
// Created: 2024-02-16
//
// License: BSD-3-Clause

package runtime

import "unsafe"

var OoscRoutines map[uint64]*OoscRoutine
var OoscRoutinesLock = mutex{}

var projectPath string

// var atomicRecordingDisabled = false

// OoscRoutine is a struct to store the trace of a routine
// Fields:
//   - id uint64: the id of the routine
//   - maxObjectId uint64: the maximum id of elements in the trace
//   - G *g: the g struct of the routine
//   - Trace []traceElem: the trace of the routine
//   - replayID int: when used in reply, id of the new routine in the replayed trace
//   - parkOn []unsafe.Pointer: list of elements the routine was last parked on
//   - parkPos string: position of last park in form file:line
//   - parkForeverReplay bool: if true, routine parks forever based on replay
//   - createdAtFile: file of fork or <autogenerated>
//   - createdAtLine: line of fork
type OoscRoutine struct {
	id                   uint64
	maxObjectId          uint64
	G                    *g
	Trace                []traceElem
	replayID             int
	parkOn               []unsafe.Pointer
	parkPos              string
	parkForeverReplay    bool
	wokenButTimeout      bool
	startedWritingToFile bool
	createdAtFile        string
	createdAtLine        int32
}

// Create a new oosc routine
// Params:
//   - g: the g struct of the routine
//   - replayRoutine int: when used in reply, id of the new routine in the replayed trace
//   - the replay ids of the routines forked from this routine
//   - caf: file of fork or <autogenerated>
//   - cal: line of fork
//
// Return:
//   - the new oosc routine
func newOoscRoutine(g *g, replayRoutine int, caf string, cal int32) *OoscRoutine {
	// ignore the internal routines that are run before the main/test function starts
	if ooscTracingDisabled {
		return &OoscRoutine{
			id:            0,
			maxObjectId:   0,
			G:             g,
			Trace:         make([]traceElem, 0),
			replayID:      replayRoutine,
			parkOn:        make([]unsafe.Pointer, 0),
			createdAtFile: caf,
			createdAtLine: cal,
		}
	}

	ooscRoutineInfo := &OoscRoutine{
		id:            GetNewOoscRoutineID(),
		maxObjectId:   0,
		G:             g,
		Trace:         make([]traceElem, 0),
		replayID:      replayRoutine,
		parkOn:        make([]unsafe.Pointer, 0),
		createdAtFile: caf,
		createdAtLine: cal,
	}

	lock(&OoscRoutinesLock)
	defer unlock(&OoscRoutinesLock)

	if OoscRoutines == nil {
		OoscRoutines = make(map[uint64]*OoscRoutine)
	}

	OoscRoutines[ooscRoutineInfo.id] = ooscRoutineInfo

	return ooscRoutineInfo
}

// setCurrentRoutineToActive will set the id of the current routine to a valid id
// and add it to OoscRoutine
// If it already contains a valid id, do nothing.
// Call when tracing gets enabled
func setCurrentRoutineToActive() {
	g := getg()

	if g.ooscRoutineInfo.id != 0 {
		return
	}

	g.ooscRoutineInfo.id = GetNewOoscRoutineID()

	lock(&OoscRoutinesLock)
	defer unlock(&OoscRoutinesLock)

	if OoscRoutines == nil {
		OoscRoutines = make(map[uint64]*OoscRoutine)
	}

	OoscRoutines[g.ooscRoutineInfo.id] = g.ooscRoutineInfo
}

// Add an element to the trace of the current routine
// Params:
//   - elem: the element to add
//
// Return:
//   - the index of the element in the trace
func (gi *OoscRoutine) addToTrace(elem traceElem) int {
	// never needed in actual code, without it the compiler tests fail
	if gi == nil {
		return -1
	}

	gi.Trace = append(gi.Trace, elem)
	return len(gi.Trace) - 1
}

func (gi *OoscRoutine) getElement(index int) traceElem {
	return gi.Trace[index]
}

func (gi *OoscRoutine) getPosCreated() string {
	return posToString(gi.createdAtFile, int(gi.createdAtLine))
}

func (gi *OoscRoutine) getLastElement() traceElem {
	return gi.Trace[len(gi.Trace)-1]
}

// Update an element in the trace of the current routine
// Params:
//   - index: the index of the element to update
//   - elem: the new element
func (gi *OoscRoutine) updateElement(index int, elem traceElem) {
	if ooscTracingDisabled {
		return
	}

	if gi == nil {
		return
	}

	if gi.Trace == nil {
		panic("Tried to update element in nil trace")
	}

	if index >= len(gi.Trace) {
		panic("Tried to update element out of bounds")
	}

	gi.Trace[index] = elem
}

// Get the current routine
// Return:
//   - *OoscRoutine: the current routine
func currentGoRoutineInfo() *OoscRoutine {
	return getg().ooscRoutineInfo
}

// GetRoutineID gets the id of the current routine
// Return:
//   - int: id of the current routine, 0 if current routine is nil
func GetRoutineID() int {
	currentRoutine := currentGoRoutineInfo()
	if currentRoutine == nil {
		return 0
	}
	return int(currentRoutine.id)
}

// GetReplayRoutineID returns the replay id of the current routine
// Return:
//   - int: replay id of the current routine, 0 if current routine is nil
func GetReplayRoutineID() int {
	currentRoutine := currentGoRoutineInfo()
	if currentRoutine == nil {
		return 0
	}
	return int(currentRoutine.replayID)
}

// OOSC-FILE-END
