// GOCCT-FILE_START

// Copyright (c) 2024 Erik Kassubek
//
// File: gocct_routine.go
// Brief: Functionality for the routines
//
// Author: Erik Kassubek
// Created: 2024-02-16
//
// License: BSD-3-Clause

package runtime

import "internal/runtime/atomic"

var numberFunctions atomic.Int64

// TODO: add to replay?

// var atomicRecordingDisabled = false

// GoCCTTraceFunctionStart is a struct to store the start of a function
// Fields:
//   - t int: time
//   - name string: name of the function
//   - fileCal string: file of the function call
//   - lineCal int: line of the function call
//   - fileDef string: file of the function definition
//   - lineDef int: line of the function definition
type GoCCTTraceFunctionStart struct {
	t        int64
	name     string
	fileCall string
	lineCall int
	fileDef  string
	lineDef  int
}

// GoCCTFunctionStart is a struct to store the end of a function
// Fields:
//   - t: int
type GoCCTTraceFunctionReturn struct {
	t int64
}

// GoCCTFunctionCall adds a function stall to the trace
func gocctFunctionCall() {
	if GoCCTTracingDisabled {
		return
	}

	timer := GetNextTimeStep()

	pc, fileDef, lineDef, _ := Caller(1)
	funcName := FuncForPC(pc).Name()

	// fix return of init
	if funcName == "main.main" {
		for numberFunctions.Load() > 0 {
			gocctFunctionReturn()
		}
	}

	_, fileCall, lineCall, _ := Caller(2)

	// for go f(), call of f cannot be determined by Caller
	// but is equal to the call of the creation of the routine
	if hasSuffix(fileCall, ".s") {
		gi := currentGoRoutineInfo()
		fileCall = gi.forkFile
		lineCall = int(gi.forkLine)
	}

	if GoCCTIgnore(fileDef) {
		return
	}

	elem := GoCCTTraceFunctionStart{
		t:        timer,
		name:     funcName,
		fileCall: fileCall,
		lineCall: lineCall,
		fileDef:  fileDef,
		lineDef:  lineDef,
	}

	numberFunctions.Add(1)

	insertIntoTrace(elem)
}

func gocctFunctionCallInit() {
	if GoCCTTracingDisabled {
		return
	}

	timer := GetNextTimeStep()

	funcName := "main.init"

	elem := GoCCTTraceFunctionStart{
		t:        timer,
		name:     funcName,
		fileCall: "<autogenerated>",
		lineCall: 0,
		fileDef:  "<autogenerated>",
		lineDef:  0,
	}

	numberFunctions.Add(1)

	insertIntoTrace(elem)
}

// GoCCTFunctionCall adds a function stall to the trace
//
// Returns:
//   - index of the operation in the trace
func gocctFunctionReturn() {
	if GoCCTTracingDisabled {
		return
	}

	if numberFunctions.Load() == 0 {
		return
	}

	timer := GetNextTimeStep()

	elem := GoCCTTraceFunctionReturn{
		t: timer,
	}

	numberFunctions.Add(-1)

	insertIntoTrace(elem)
}

// Get a string representation of the trace element
//
// Returns:
//   - string: the string representation
func (elem GoCCTTraceFunctionStart) toString() string {
	return buildTraceElemString("F", elem.t, elem.name, posToString(elem.fileDef, elem.lineDef), posToString(elem.fileCall, elem.lineCall))
}

// Get a string representation of the trace element
//
// Returns:
//   - string: the string representation
func (self GoCCTTraceFunctionReturn) toString() string {
	return buildTraceElemString("R", self.t)
}

// getOperation is a getter for the operation
//
// Returns:
//   - Operation: the operation
func (elem GoCCTTraceFunctionStart) getOperation() Operation {
	return OperationFunctionCall
}

// getOperation is a getter for the operation
//
// Returns:
//   - Operation: the operation
func (self GoCCTTraceFunctionReturn) getOperation() Operation {
	return OperationFunctionReturn
}

// hasCommit returns if the event has committed
//
// Returns:
//   - bool: true if committed, false if only request
func (self GoCCTTraceFunctionStart) hasCommit() bool {
	return true
}

// hasCommit returns if the event has committed
//
// Returns:
//   - bool: true if committed, false if only request
func (self GoCCTTraceFunctionReturn) hasCommit() bool {
	return true
}

// resource returns the resources for the operation. Can only be greater 1 for select
//
// Returns:
//   - []GoCCTTraceResource: recources
func (self GoCCTTraceFunctionStart) resource() []GoCCTTraceResource {
	return []GoCCTTraceResource{}
}

// resource returns the resources for the operation. Can only be greater 1 for select
//
// Returns:
//   - []GoCCTTraceResource: recources
func (self GoCCTTraceFunctionReturn) resource() []GoCCTTraceResource {
	return []GoCCTTraceResource{}
}
