// GOCDR-FILE_START

// Copyright (c) 2024 Erik Kassubek
//
// File: gocdr_routine.go
// Brief: Functionality for the routines
//
// Author: Erik Kassubek
// Created: 2024-02-16
//
// License: BSD-3-Clause

package runtime

import "internal/runtime/atomic"

var numberFunctions atomic.Int64

// TODO: add to replay?

// var atomicRecordingDisabled = false

// GoCDRTraceFunctionStart is a struct to store the start of a function
// Fields:
//   - t int: time
//   - name string: name of the function
//   - fileCal string: file of the function call
//   - lineCal int: line of the function call
//   - fileDef string: file of the function definition
//   - lineDef int: line of the function definition
type GoCDRTraceFunctionStart struct {
	t        int64
	name     string
	fileCall string
	lineCall int
	fileDef  string
	lineDef  int
}

// GoCDRFunctionStart is a struct to store the end of a function
// Fields:
//   - t: int
type GoCDRTraceFunctionReturn struct {
	t int64
}

// GoCDRFunctionCall adds a function stall to the trace
func gocdrFunctionCall() {
	if GoCDRTracingDisabled {
		return
	}

	timer := GetNextTimeStep()

	pc, fileDef, lineDef, _ := Caller(1)
	funcName := FuncForPC(pc).Name()

	// fix return of init
	if funcName == "main.main" {
		for numberFunctions.Load() > 0 {
			gocdrFunctionReturn()
		}
	}

	_, fileCall, lineCall, _ := Caller(2)

	// for go f(), call of f cannot be determined by Caller
	// but is equal to the call of the creation of the routine
	if hasSuffix(fileCall, ".s") {
		gi := currentGoRoutineInfo()
		fileCall = gi.forkFile
		lineCall = int(gi.forkLine)
	}

	if GoCDRIgnore(fileDef) {
		return
	}

	elem := GoCDRTraceFunctionStart{
		t:        timer,
		name:     funcName,
		fileCall: fileCall,
		lineCall: lineCall,
		fileDef:  fileDef,
		lineDef:  lineDef,
	}

	numberFunctions.Add(1)

	insertIntoTrace(elem)
}

func gocdrFunctionCallInit() {
	if GoCDRTracingDisabled {
		return
	}

	timer := GetNextTimeStep()

	funcName := "main.init"

	elem := GoCDRTraceFunctionStart{
		t:        timer,
		name:     funcName,
		fileCall: "<autogenerated>",
		lineCall: 0,
		fileDef:  "<autogenerated>",
		lineDef:  0,
	}

	numberFunctions.Add(1)

	insertIntoTrace(elem)
}

// GoCDRFunctionCall adds a function stall to the trace
//
// Returns:
//   - index of the operation in the trace
func gocdrFunctionReturn() {
	if GoCDRTracingDisabled {
		return
	}

	if numberFunctions.Load() == 0 {
		return
	}

	timer := GetNextTimeStep()

	elem := GoCDRTraceFunctionReturn{
		t: timer,
	}

	numberFunctions.Add(-1)

	insertIntoTrace(elem)
}

// Get a string representation of the trace element
//
// Returns:
//   - string: the string representation
func (elem GoCDRTraceFunctionStart) toString() string {
	return buildTraceElemString("F", elem.t, elem.name, posToString(elem.fileDef, elem.lineDef), posToString(elem.fileCall, elem.lineCall))
}

// Get a string representation of the trace element
//
// Returns:
//   - string: the string representation
func (self GoCDRTraceFunctionReturn) toString() string {
	return buildTraceElemString("R", self.t)
}

// getOperation is a getter for the operation
//
// Returns:
//   - Operation: the operation
func (elem GoCDRTraceFunctionStart) getOperation() Operation {
	return OperationFunctionCall
}

// getOperation is a getter for the operation
//
// Returns:
//   - Operation: the operation
func (self GoCDRTraceFunctionReturn) getOperation() Operation {
	return OperationFunctionReturn
}

// hasCommit returns if the event has committed
//
// Returns:
//   - bool: true if committed, false if only request
func (self GoCDRTraceFunctionStart) hasCommit() bool {
	return true
}

// hasCommit returns if the event has committed
//
// Returns:
//   - bool: true if committed, false if only request
func (self GoCDRTraceFunctionReturn) hasCommit() bool {
	return true
}

// resource returns the resources for the operation. Can only be greater 1 for select
//
// Returns:
//   - []GoCDRTraceResource: recources
func (self GoCDRTraceFunctionStart) resource() []GoCDRTraceResource {
	return []GoCDRTraceResource{}
}

// resource returns the resources for the operation. Can only be greater 1 for select
//
// Returns:
//   - []GoCDRTraceResource: recources
func (self GoCDRTraceFunctionReturn) resource() []GoCDRTraceResource {
	return []GoCDRTraceResource{}
}
