// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/at_fstatat2.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/at_fstatat2.go:1
// Copyright 2022 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build freebsd || (linux && (loong64 || mips64 || mips64le))

package unix

import "syscall"

func Fstatat(dirfd int, path string, stat *syscall.Stat_t, flags int) error {
	return syscall.Fstatat(dirfd, path, stat, flags)
}
