// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/faccessat_syscall.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/faccessat_syscall.go:1
// Copyright 2024 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build aix || linux

package unix

import "syscall"

var faccessat = syscall.Faccessat
