// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/kernel_version_other.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/kernel_version_other.go:1
// Copyright 2022 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build !freebsd && !linux && !solaris

package unix

func KernelVersion() (major int, minor int) {
	return 0, 0
}
