// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/renameat_sysnum_linux.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/renameat_sysnum_linux.go:1
// Copyright 2025 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build linux && !(loong64 || riscv64)

package unix

import "syscall"

const (
	renameatTrap uintptr = syscall.SYS_RENAMEAT
)
