// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/syscall.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/syscall.go:1
// Copyright 2024 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package unix

// Single-word zero for use when we need a valid pointer to 0 bytes.
var _zero uintptr
