// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/sysnum_linux_mipsx.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/sysnum_linux_mipsx.go:1
// Copyright 2016 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build mips || mipsle

package unix

const (
	getrandomTrap       uintptr = 4353
	copyFileRangeTrap   uintptr = 4360
	pidfdSendSignalTrap uintptr = 4424
	pidfdOpenTrap       uintptr = 4434
	openat2Trap         uintptr = 4437
)
