// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/sysnum_linux_ppc64x.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/sysnum_linux_ppc64x.go:1
// Copyright 2014 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build ppc64 || ppc64le

package unix

const (
	getrandomTrap       uintptr = 359
	copyFileRangeTrap   uintptr = 379
	pidfdSendSignalTrap uintptr = 424
	pidfdOpenTrap       uintptr = 434
	openat2Trap         uintptr = 437
)
