// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/utimes.go

//line /home/erik/Uni/Advocate/goPatch/src/internal/syscall/unix/utimes.go:1
// Copyright 2025 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build unix && !wasip1

package unix

import (
	"syscall"
	_ "unsafe" // for //go:linkname
)

//go:linkname Utimensat syscall.utimensat
func Utimensat(dirfd int, path string, times *[2]syscall.Timespec, flag int) error
