// Code generated by go tool dist; DO NOT EDIT.

// This is a bootstrap copy of /home/erik/Uni/Advocate/goPatch/src/cmd/compile/internal/ssa/_gen/go.mod

//line /home/erik/Uni/Advocate/goPatch/src/cmd/compile/internal/ssa/_gen/go.mod:1
module _gen

go 1.24

require golang.org/x/tools v0.27.0
